export const LANGS = ['en', 'fr', 'es'];

export const content = {
  en: {
    label: 'EN',
    htmlLang: 'en',
    title: 'Keel Systems',
    heroHeadline: 'Every business has that one thing somebody does by hand every week.',
    heroSub: 'I build the software that does it instead. Quotes, callbacks, forms, reports, the same answer typed for the hundredth time.',
    triggersHeading: 'Does any of this sound familiar?',
    triggersLead: 'Most of what a business loses, it already had.',
    triggers: [
      "The phone rings while I'm with a customer, and by the time I call back they've booked somewhere else.",
      'I send the quote and then I never hear back, and I never find out why.',
      'Somebody does not show up, the slot sits empty, and nobody fills it.',
      "Half my week is chasing people for paperwork they already said they'd send.",
      'There are customers who should have come back by now and nobody noticed they did not.',
      "If I'm away for a week, the whole thing stops.",
    ],
    triggersClose: "If one of these is yours, that's the conversation. If yours is not on the list, it probably still is.",
    howHeading: 'How it works',
    steps: [
      { title: 'A conversation', body: 'Thirty minutes, in person or on a call. I watch how one thing actually gets done today. Free.' },
      { title: 'One thing, built', body: 'I build the piece that removes the most expensive manual step we found. I show you a few ways to scope it, starting at two weeks. Fixed price, paid on delivery, and only if it does what I said it would.' },
      { title: 'I keep it alive', body: 'A monthly fee so it stays maintained, gets fixed the day it breaks, and never becomes one more thing you own and nobody understands.' },
    ],
    proofHeading: 'Already running',
    proofItems: [
      { title: 'Actor Manager', body: 'An app for tracking auditions and bookings. Someone uses it every day to run their own work.' },
      { title: 'Inbox Gatekeeper', body: 'It reads an inbox and separates the messages that are actually someone trying to reach you from everything else.' },
    ],
    aboutHeading: 'Who I am',
    aboutParas: [
      'I am Esteban. I build software in English, French and Spanish, based in Gatineau and working both sides of the river.',
      'I am building my first case studies right now, so I am taking on a small number of projects at a price that reflects that. What I want back is a result I can point to.',
    ],
    ctaLabel: 'Start with a conversation',
  },

  fr: {
    label: 'FR',
    htmlLang: 'fr',
    title: 'Keel Systems',
    heroHeadline: "Chaque entreprise a une affaire que quelqu'un fait à la main chaque semaine.",
    heroSub: 'Moi, je bâtis le logiciel qui la fait à sa place. Les soumissions, les rappels, les formulaires, les rapports, la même réponse tapée pour la centième fois.',
    triggersHeading: 'Est-ce que ça vous parle?',
    triggersLead: "La plupart de ce qu'une entreprise perd, elle l'avait déjà.",
    triggers: [
      'Le téléphone sonne pendant que je suis avec un client, et quand je rappelle, la personne a déjà réservé ailleurs.',
      "J'envoie la soumission et je n'ai plus jamais de nouvelles, et je ne sais jamais pourquoi.",
      'Quelqu’un ne se présente pas, la plage horaire reste vide, et personne ne la remplit.',
      "La moitié de ma semaine, je cours après du monde pour des papiers qu'ils avaient promis de m'envoyer.",
      "Il y a des clients qui auraient dû revenir depuis longtemps et personne n'a remarqué qu'ils ne sont pas revenus.",
      'Si je pars une semaine, tout arrête.',
    ],
    triggersClose: "Si une de ces phrases est la vôtre, c'est de ça qu'on devrait parler. Si la vôtre n'est pas dans la liste, elle y a probablement sa place aussi.",
    howHeading: 'Comment ça marche',
    steps: [
      { title: 'Une conversation', body: "Trente minutes, en personne ou au téléphone. Je regarde comment une affaire se fait vraiment aujourd'hui. Gratuit." },
      { title: 'Une chose, bâtie', body: "Je bâtis le morceau qui enlève l'étape manuelle la plus coûteuse qu'on a trouvée. Je vous montre quelques façons de cadrer le projet, à partir de deux semaines. Prix fixe, payable à la livraison, et seulement si ça fait ce que j'ai dit." },
      { title: 'Je la garde en vie', body: "Un montant mensuel pour qu'elle reste entretenue, que je la répare le jour où elle brise, et qu'elle ne devienne jamais une autre affaire que vous possédez et que personne ne comprend." },
    ],
    proofHeading: 'Déjà en marche',
    proofItems: [
      { title: 'Actor Manager', body: "Une application pour gérer les auditions et les contrats. Quelqu'un s'en sert chaque jour pour son propre travail." },
      { title: 'Inbox Gatekeeper', body: "Il lit une boîte de courriels et sépare les messages de quelqu'un qui essaie vraiment de vous joindre du reste." },
    ],
    aboutHeading: 'Qui je suis',
    aboutParas: [
      "Je m'appelle Esteban. Je développe des logiciels en français, en anglais et en espagnol, à partir de Gatineau, des deux côtés de la rivière.",
      "Je bâtis mes premiers cas concrets en ce moment, alors je prends un petit nombre de projets à un prix qui le reflète. Ce que je veux en retour, c'est un résultat que je peux montrer.",
    ],
    ctaLabel: 'Commencer par une conversation',
  },

  es: {
    label: 'ES',
    htmlLang: 'es',
    title: 'Keel Systems',
    heroHeadline: 'Toda empresa tiene esa cosa que alguien hace a mano todas las semanas.',
    heroSub: 'Yo construyo el software que la hace. Las cotizaciones, las llamadas de vuelta, los formularios, los reportes, la misma respuesta escrita por centésima vez.',
    triggersHeading: '¿Le suena conocido?',
    triggersLead: 'La mayor parte de lo que un negocio pierde, ya lo tenía.',
    triggers: [
      'El teléfono suena mientras estoy con un cliente, y cuando devuelvo la llamada ya reservaron en otro lado.',
      'Mando la cotización y nunca me vuelven a contestar, y nunca sé por qué.',
      'Alguien no llega, el espacio queda vacío, y nadie lo vuelve a llenar.',
      'La mitad de mi semana es persiguiendo gente por papeles que ya habían dicho que me mandaban.',
      'Hay clientes que ya deberían haber vuelto y nadie se dio cuenta de que no volvieron.',
      'Si me voy una semana, todo se para.',
    ],
    triggersClose: 'Si alguna de estas es la suya, de eso deberíamos hablar. Si la suya no está en la lista, seguramente también cabe aquí.',
    howHeading: 'Cómo funciona',
    steps: [
      { title: 'Una conversación', body: 'Treinta minutos, en persona o por llamada. Miro cómo se hace de verdad una sola cosa hoy. Gratis.' },
      { title: 'Una cosa, construida', body: 'Construyo la pieza que quita el paso manual más caro que encontramos. Le muestro algunas formas de definir el alcance, desde dos semanas. Precio fijo, se paga en la entrega, y solo si hace lo que dije.' },
      { title: 'Yo la mantengo viva', body: 'Una cuota mensual para que siga mantenida, la arreglo el día que se daña, y nunca se convierta en una cosa más que usted tiene y nadie entiende.' },
    ],
    proofHeading: 'Ya funcionando',
    proofItems: [
      { title: 'Actor Manager', body: 'Una aplicación para manejar audiciones y contratos. Alguien la usa todos los días para su propio trabajo.' },
      { title: 'Inbox Gatekeeper', body: 'Lee un buzón de correo y separa los mensajes de alguien que de verdad está tratando de contactarlo del resto.' },
    ],
    aboutHeading: 'Quién soy',
    aboutParas: [
      'Me llamo Esteban. Desarrollo software en español, inglés y francés, desde Gatineau, Canadá.',
      'Estoy construyendo mis primeros casos ahora mismo, así que estoy tomando un número pequeño de proyectos a un precio que lo refleja. Lo que quiero a cambio es un resultado que pueda mostrar.',
    ],
    ctaLabel: 'Empezar con una conversación',
  },
};
